apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mqtt-app
  name: mqtt-app
  namespace: home-assistent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-app
  template:
    metadata:
      labels:
        app: mqtt-app
    spec:
      containers:
      - name: mqtt-app
        image: eclipse-mosquitto:2.0.14
        resources:
          requests:
            memory: "80Mi"
            cpu: "200m"
          limits:
            memory: "424Mi"
            cpu: "700m"
        volumeMounts:
        - name: volv
          mountPath: /mosquitto
        ports:
        - containerPort: 1883
        readinessProbe:
          tcpSocket:
            port: 1883
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 1883
         initialDelaySeconds: 15
         periodSeconds: 20
      volumes:
      - name: volv
        persistentVolumeClaim:
          claimName: mqtt-pvc
