apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: assistant-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10G

