apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: assistant-pvc
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10G
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt-pvc
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10G
