apiVersion: v1
kind: Service
metadata:
  name: assistant-service
  namespace: home-assistant
spec:
  selector:
    app: assistant-app
  ports:
    - port: 8123
      targetPort: 8123
---

apiVersion: v1
kind: Service
metadata:
  name: mtt-service
  namespace: home-assistant
spec:
  selector:
    app: mqtt-app
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: websockets
      port: 9001
      targetPort: 9001
